### ISSUE TITLE
Change the activity backend to reflect the new submission form

### ISSUE THREAD

**Issue by slowe** [unawe/astroEDU#11]
There is a new (version 9) version of the form that collects the information. This will require deletions, additions, and modifications to database fields for an activity. I'm not sure how to do these without breaking everything.
[astroEDU_submissionform_ver9.pdf](https://github.com/unawe/astroEDU/files/580748/astroEDU_submissionform_ver9.pdf)

**Comment by vehrlich** [comment]
For versioning of models : https://django-reversion.readthedocs.io/en/stable/index.html
But maybe versioning of form will be enough

**Comment by thilina-heenatigala** [comment]
@vehrlich Can we start this? We need to change the backend to reflect the new submission form. Once you changed it, some activities will have empty slots. But we have an intern for a couple of weeks and he will be able to update all the activities.

**Comment by unawe** [comment]
@vehrlich : How long do you think that this would take to do?  P. Russo.

**Comment by vehrlich** [comment]
Solved
